site_name: MkDocs Practical 2
site_description: MkDocs practical project with custom Jinja2 templates and modern design
site_author: Mahmod Ahmad
site_url: https://mahmodahmad003sy.github.io/mkdocs-site/

theme:
  name: material
  custom_dir: custom_theme
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - def_list

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Features: features.md
  - React Demo: react-demo.md
  - About: about.md

copyright: Copyright &copy; 2024 Mahmod Ahmad. All rights reserved.
