name: build and deploy of static site

on:
  push:
jobs:
  build:
    name: build and deply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: install mkdocs
        run: pip install mkdocs
      - name: build
        run: mkdocs build

      - name: install ssh
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{secrets.PRIVATE_SSH_KEY}}" > ~/.ssh/id_rsa
          echo "${{secrets.KNOWN_HOSTS}}" > ~/.ssh/known_hosts
      - name: deploy
        run: rsync --archive --stats site ${{ secrets.REMOTE_DEST}}
